### ISSUE TITLE
Crash when built by angular-cli with --prod flag

### ISSUE THREAD

**Issue by xwb1989** [ceolter/ag-grid-enterprise#39]
No really sure whether this is the right place to raise the issue, as it might be caused by `angular-cli`. However, as the error is from `ag-grid-enterprise`, I opened the issue here.

The build process is fine, but when load the app into browser, following error can be found:

`TypeError: this.cbPivotMode.setSelected is not a function
    at b.init (http://localhost:4200/main.js:30:3445)
    at eval (http://localhost:4200/main.js:42:10584)
    at Array.forEach (native)
    at eval (http://localhost:4200/main.js:42:10553)
    at Array.forEach (native)
    at a.postConstruct (http://localhost:4200/main.js:42:10432)
    at a.wireBeans (http://localhost:4200/main.js:42:8118)
    at a.wireBean (http://localhost:4200/main.js:42:8017)
    at b.addComponent (http://localhost:4200/main.js:29:25018)
    at b.init (http://localhost:4200/main.js:29:24571)`

A minimal example to reproduce this error can be found here: https://github.com/xwb1989/ag-grid-test

**Comment by ceolter** [comment]
you are probably using incompatible version of ag-grid.

best is try it with versions 5.0.x of both ag-grid and ag-grid-enterprise.

the cbPivotMode.setSelected() is in ag-Grid, and is getting called from ag-grid-enterprise. it was a new addition, so i'm guessing your ag-grid-enterprise is out of date.

**Comment by xwb1989** [comment]
I'm using both 5.0.0 and it's working fine when it's built in dev mode

**Comment by ceolter** [comment]
this is now fixed. it was due to ag-Grid not working when then code was minified. latest version has this issue resolved.
