### ISSUE TITLE
setColumnsVisible issue

### ISSUE THREAD

**Issue by GalitTugi** [ceolter/ag-grid-enterprise#93]
Hello,
I call the columnApi function setColumnsVisible, with tow columns that exist on the grid.
The visibility does change, but an error occurs.

The problem doesn't happen when I send only one column as a parameter (event if it's for the same function, in an array).

The error received:
Uncaught TypeError: Cannot read property 'colId' of undefined
    at eval (eval at <anonymous> (http://localhost:3000/app.4a205d571d726c3a2df0.js:516:2), <anonymous>:235:29)
    at eval (eval at <anonymous> (http://localhost:3000/app.4a205d571d726c3a2df0.js:722:2), <anonymous>:1019:14)
    at Array.forEach (native)
    at EventService.dispatchEvent (eval at <anonymous> (http://localhost:3000/app.4a205d571d726c3a2df0.js:722:2), <anonymous>:1018:23)
    at ColumnController.actionOnGridColumns (eval at <anonymous> (http://localhost:3000/app.4a205d571d726c3a2df0.js:722:2), <anonymous>:4242:28)
    at ColumnController.setColumnsVisible (eval at <anonymous> (http://localhost:3000/app.4a205d571d726c3a2df0.js:722:2), <anonymous>:4176:15)
    at ColumnApi.setColumnsVisible (eval at <anonymous> (http://localhost:3000/app.4a205d571d726c3a2df0.js:722:2), <anonymous>:3554:96)
    at Constructor.setColumnsVisible (eval at <anonymous> (http://localhost:3000/app.4a205d571d726c3a2df0.js:516:2), <anonymous>:792:20)
    at Constructor.proxiedMethod [as setColumnsVisible] (eval at <anonymous> (http://localhost:3000/app.4a205d571d726c3a2df0.js:6022:2), <anonymous>:44:30)
    at Constructor.allItemsClick (eval at <anonymous> (http://localhost:3000/app.4a205d571d726c3a2df0.js:3353:2), <anonymous>:91:18)

**Comment by ceolter** [comment]
please either provide plunker with this recreated, or give steps on how to recreate with one of the documentation demo's (you could send api command from console to a demo)
